[package]
name = "goertzel"
version = "0.0.0"
authors = ["Matt McPherrin <git@mcpherrin.ca>"]
repository = "https://github.com/mcpherrinm/goertzel.git"
keywords = ["dsp", "goertzel", "fft", "fourier"]
license = "MIT"
description = "An implementation of Goertzel's Algoritm"
